[project]
name = "midigen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "miditok>=3.0.6.post1",
    "symusic>=0.5.9",
    "torch>=2.9.1",
    "transformers>=4.57.5",
]
